
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN}
    preferIpAddress: ${EUREKA_PREFER_IP:true}
    nonSecurePort: ${PORT}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

mensaje:
  global: "Configuracion entregada por el Config Server - Ferreteria Molina"
