
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:ferreteria}?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


app:
  jwt:
    secret: ZmVycmV0ZXJpYS1tb2xpbmEtc2VjcmV0LWtleS1zdXBlci1zZWd1cmEtMjAyNg==
    expiration: 86400000

logging:
  level:
    com.ferreteria.auth: DEBUG
